export const CREATE_VOUCHER_REQUEST = "CREATE_VOUCHER_REQUEST";
export const CREATE_VOUCHER_SUCCESS = "CREATE_VOUCHER_SUCCESS";
export const CREATE_VOUCHER_FAIL = "CREATE_VOUCHER_FAIL";

export const VOUCHER_DETAILS_REQUEST = "VOUCHER_DETAILS_REQUEST";
export const VOUCHER_DETAILS_SUCCESS = "VOUCHER_DETAILS_SUCCESS";
export const VOUCHER_DETAILS_FAIL = "VOUCHER_DETAILS_FAIL";

export const VOUCHER_BUY_REQUEST = "VOUCHER_BUY_REQUEST";
export const VOUCHER_BUY_SUCCESS = "VOUCHER_BUY_SUCCESS";
export const VOUCHER_BUY_FAIL = "VOUCHER_BUY_FAIL";
export const VOUCHER_BUY_RESET = "VOUCHER_BUY_RESET";

export const VOUCHER_PAY_REQUEST = "VOUCHER_PAY_REQUEST";
export const VOUCHER_PAY_SUCCESS = "VOUCHER_PAY_SUCCESS";
export const VOUCHER_PAY_FAIL = "VOUCHER_PAY_FAIL";