export const RETURNS_REQUEST = "RETURNS_REQUEST";
export const RETURNS_SUCCESS = "RETURNS_SUCCESS";
export const RETURNS_FAIL = "RETURNS_FAIL";

export const RETURNS_COUNT_REQUEST = "RETURNS_COUNT_REQUEST";
export const RETURNS_COUNT_SUCCESS = "RETURNS_COUNT_SUCCESS";
export const RETURNS_COUNT_FAIL = "RETURNS_COUNT_FAIL";

export const RETURNS_RESTORE_REQUEST = "RETURNS_RESTORE_REQUEST";
export const RETURNS_RESTORE_SUCCESS = "RETURNS_RESTORE_SUCCESS";
export const RETURNS_RESTORE_FAIL = "RETURNS_RESTORE_FAIL";

export const RETURNS_DETAILS_REQUEST = "RETURNS_DETAILS_REQUEST";
export const RETURNS_DETAILS_SUCCESS = "RETURNS_DETAILS_SUCCESS";
export const RETURNS_DETAILS_FAIL ="RETURNS_DETAILS_FAILS";